# Generated by Django 5.1.3 on 2024-11-28 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0003_alter_cat_breed_alter_cat_name_alter_target_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="country",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(100),
                ],
            ),
        ),
    ]
